const zodiacSigns = [
  {
    name: 'Aries',
    symbol: '♈',
    element: 'Fire',
    dates: 'March 21 - April 19',
    traits: ['Energetic', 'Confident', 'Pioneering', 'Impulsive'],
    description: 'Aries are natural leaders with a pioneering spirit. They are energetic, confident, and always ready to take on new challenges.',
    compatibility: ['Leo', 'Sagittarius', 'Gemini', 'Aquarius'],
    luckyNumbers: [1, 8, 17],
    luckyColors: ['Red', 'Orange'],
    planet: 'Mars',
  },
  {
    name: 'Taurus',
    symbol: '♉',
    element: 'Earth',
    dates: 'April 20 - May 20',
    traits: ['Reliable', 'Patient', 'Practical', 'Stubborn'],
    description: 'Taurus individuals are known for their reliability and practical nature. They value stability and have a strong appreciation for beauty.',
    compatibility: ['Virgo', 'Capricorn', 'Cancer', 'Pisces'],
    luckyNumbers: [2, 6, 9, 12, 24],
    luckyColors: ['Green', 'Pink'],
    planet: 'Venus',
  },
  {
    name: 'Gemini',
    symbol: '♊',
    element: 'Air',
    dates: 'May 21 - June 20',
    traits: ['Adaptable', 'Curious', 'Communicative', 'Inconsistent'],
    description: 'Geminis are versatile and curious individuals who love to communicate and learn new things. They are adaptable but can be inconsistent.',
    compatibility: ['Libra', 'Aquarius', 'Aries', 'Leo'],
    luckyNumbers: [5, 7, 14, 23],
    luckyColors: ['Yellow', 'Silver'],
    planet: 'Mercury',
  },
  {
    name: 'Cancer',
    symbol: '♋',
    element: 'Water',
    dates: 'June 21 - July 22',
    traits: ['Nurturing', 'Emotional', 'Intuitive', 'Protective'],
    description: 'Cancers are deeply emotional and intuitive. They are natural nurturers who value family and home above all else.',
    compatibility: ['Scorpio', 'Pisces', 'Taurus', 'Virgo'],
    luckyNumbers: [2, 7, 11, 16, 20, 25],
    luckyColors: ['White', 'Silver'],
    planet: 'Moon',
  },
  {
    name: 'Leo',
    symbol: '♌',
    element: 'Fire',
    dates: 'July 23 - August 22',
    traits: ['Confident', 'Generous', 'Creative', 'Dramatic'],
    description: 'Leos are natural performers who love to be in the spotlight. They are generous, creative, and have a strong sense of pride.',
    compatibility: ['Aries', 'Sagittarius', 'Gemini', 'Libra'],
    luckyNumbers: [1, 3, 10, 19],
    luckyColors: ['Gold', 'Orange'],
    planet: 'Sun',
  },
  {
    name: 'Virgo',
    symbol: '♍',
    element: 'Earth',
    dates: 'August 23 - September 22',
    traits: ['Analytical', 'Practical', 'Helpful', 'Critical'],
    description: 'Virgos are detail-oriented perfectionists who strive for excellence in everything they do. They are practical and helpful.',
    compatibility: ['Taurus', 'Capricorn', 'Cancer', 'Scorpio'],
    luckyNumbers: [6, 15, 20, 24],
    luckyColors: ['Navy Blue', 'Grey'],
    planet: 'Mercury',
  },
  {
    name: 'Libra',
    symbol: '♎',
    element: 'Air',
    dates: 'September 23 - October 22',
    traits: ['Diplomatic', 'Charming', 'Balanced', 'Indecisive'],
    description: 'Libras seek harmony and balance in all aspects of life. They are diplomatic, charming, and have a strong sense of justice.',
    compatibility: ['Gemini', 'Aquarius', 'Leo', 'Sagittarius'],
    luckyNumbers: [4, 6, 13, 15, 24],
    luckyColors: ['Blue', 'Green'],
    planet: 'Venus',
  },
  {
    name: 'Scorpio',
    symbol: '♏',
    element: 'Water',
    dates: 'October 23 - November 21',
    traits: ['Intense', 'Passionate', 'Mysterious', 'Jealous'],
    description: 'Scorpios are intense and passionate individuals with a mysterious aura. They are deeply emotional and fiercely loyal.',
    compatibility: ['Cancer', 'Pisces', 'Virgo', 'Capricorn'],
    luckyNumbers: [8, 11, 18, 22],
    luckyColors: ['Deep Red', 'Black'],
    planet: 'Pluto',
  },
  {
    name: 'Sagittarius',
    symbol: '♐',
    element: 'Fire',
    dates: 'November 22 - December 21',
    traits: ['Adventurous', 'Optimistic', 'Philosophical', 'Restless'],
    description: 'Sagittarians are adventurous souls who love to explore and learn. They are optimistic, philosophical, and value freedom.',
    compatibility: ['Aries', 'Leo', 'Libra', 'Aquarius'],
    luckyNumbers: [3, 9, 15, 21, 27],
    luckyColors: ['Purple', 'Turquoise'],
    planet: 'Jupiter',
  },
  {
    name: 'Capricorn',
    symbol: '♑',
    element: 'Earth',
    dates: 'December 22 - January 19',
    traits: ['Ambitious', 'Disciplined', 'Practical', 'Pessimistic'],
    description: 'Capricorns are ambitious and disciplined individuals who work hard to achieve their goals. They are practical and responsible.',
    compatibility: ['Taurus', 'Virgo', 'Scorpio', 'Pisces'],
    luckyNumbers: [6, 9, 15, 18, 27],
    luckyColors: ['Brown', 'Black'],
    planet: 'Saturn',
  },
  {
    name: 'Aquarius',
    symbol: '♒',
    element: 'Air',
    dates: 'January 20 - February 18',
    traits: ['Independent', 'Innovative', 'Humanitarian', 'Detached'],
    description: 'Aquarians are independent thinkers who value freedom and innovation. They are humanitarian and often ahead of their time.',
    compatibility: ['Gemini', 'Libra', 'Aries', 'Sagittarius'],
    luckyNumbers: [4, 7, 11, 22, 29],
    luckyColors: ['Blue', 'Silver'],
    planet: 'Uranus',
  },
  {
    name: 'Pisces',
    symbol: '♓',
    element: 'Water',
    dates: 'February 19 - March 20',
    traits: ['Compassionate', 'Intuitive', 'Artistic', 'Escapist'],
    description: 'Pisceans are compassionate and intuitive individuals with a strong artistic nature. They are empathetic but can be escapist.',
    compatibility: ['Cancer', 'Scorpio', 'Taurus', 'Capricorn'],
    luckyNumbers: [3, 9, 12, 15, 18, 24],
    luckyColors: ['Sea Green', 'Lavender'],
    planet: 'Neptune',
  },
];

const compatibilityMatrix = {
  aries: { leo: 95, sagittarius: 90, gemini: 85, aquarius: 80, libra: 75, cancer: 60, capricorn: 55, taurus: 50, virgo: 45, scorpio: 40, pisces: 35 },
  taurus: { virgo: 95, capricorn: 90, cancer: 85, pisces: 80, scorpio: 75, leo: 60, aquarius: 55, gemini: 50, sagittarius: 45, aries: 40, libra: 35 },
  gemini: { libra: 95, aquarius: 90, aries: 85, leo: 80, sagittarius: 75, virgo: 60, pisces: 55, taurus: 50, scorpio: 45, cancer: 40, capricorn: 35 },
  cancer: { scorpio: 95, pisces: 90, taurus: 85, virgo: 80, capricorn: 75, aries: 60, libra: 55, leo: 50, aquarius: 45, gemini: 40, sagittarius: 35 },
  leo: { aries: 95, sagittarius: 90, gemini: 85, libra: 80, aquarius: 75, scorpio: 60, taurus: 55, cancer: 50, virgo: 45, capricorn: 40, pisces: 35 },
  virgo: { taurus: 95, capricorn: 90, cancer: 85, scorpio: 80, pisces: 75, gemini: 60, sagittarius: 55, aries: 50, leo: 45, libra: 40, aquarius: 35 },
  libra: { gemini: 95, aquarius: 90, leo: 85, sagittarius: 80, aries: 75, cancer: 60, capricorn: 55, virgo: 50, pisces: 45, taurus: 40, scorpio: 35 },
  scorpio: { cancer: 95, pisces: 90, virgo: 85, capricorn: 80, taurus: 75, leo: 60, aquarius: 55, libra: 50, gemini: 45, sagittarius: 40, aries: 35 },
  sagittarius: { aries: 95, leo: 90, libra: 85, aquarius: 80, gemini: 75, virgo: 60, pisces: 55, capricorn: 50, taurus: 45, cancer: 40, scorpio: 35 },
  capricorn: { taurus: 95, virgo: 90, scorpio: 85, pisces: 80, cancer: 75, libra: 60, aries: 55, sagittarius: 50, leo: 45, aquarius: 40, gemini: 35 },
  aquarius: { gemini: 95, libra: 90, aries: 85, sagittarius: 80, leo: 75, scorpio: 60, taurus: 55, cancer: 50, virgo: 45, capricorn: 40, pisces: 35 },
  pisces: { cancer: 95, scorpio: 90, taurus: 85, capricorn: 80, virgo: 75, sagittarius: 60, gemini: 55, leo: 50, aries: 45, libra: 40, aquarius: 35 },
};

module.exports = {
  zodiacSigns,
  compatibilityMatrix,
};